### ISSUE TITLE
Errors with certain inputs

### ISSUE THREAD

**Issue by otherjoel** [simmone/racket-simple-barcode#1]
```racket
(barcode-write 'png "%B%01-23-45" "t.png" #:code_type 'code128)
```

results in:

```
hash-ref: no value found for key
  key: "8"
```

Similarly if I do `(barcode-write 'png "123" "t.png" #:code_type 'code128)`, it responds with `hash-ref: no value found for key / key "7"`.

If I open `code128-lib.rkt` and do this:

```racket
(parameterize ([*front_color* "black"]
                 [*back_color* "white"]
                 [*brick_width* 3]
                 [*font_size* 3])
    (draw-code128 'png "%B%01-23-45" "t.png"))
```

Then it appears the error is coming from the second `hash-ref` on this line: https://github.com/simmone/racket-simple-barcode/blob/4afa806ff27de8e2715b15904e1f3fcec2c7f136/simple-barcode/lib/code128-lib.rkt#L379

**Comment by simmone** [comment]
get it, I'll work on this bug, thank you for report the issue.

Joel Dueck ***@***.***> 于 2022年2月25日周五 08:04写道：

**Comment by simmone** [comment]
Fixed, checksum data not treated correctly. Use raco pkg update simple-barcode to update package and verify.

**Comment by otherjoel** [comment]
Thank you the errors appear to be gone! I will test the barcodes themselves with our scanners shortly.

**Comment by otherjoel** [comment]
Scanners show the generated barcodes work properly. Thank you!

**Comment by otherjoel** [comment]
I am using this library as part of a warehouse setup project at a for-profit company. Please advise how I can send a donation for your support on behalf of my company, if possible.

**Comment by simmone** [comment]
I'm glad to hear my this little library is useful, that's enough, that is a big motivation let me maintain and refine it, have a good day.
